"""
Database-oriented constant objects derived from sentiment and ideology enums.
"""
from models.py_schemas import (
	SentimentCategoryBase,
	SentimentBase,
	IdeologyCategoryBase,
	IdeologyBase,
)

_SENTIMENT_CATEGORIES: list[SentimentCategoryBase] = [
	SentimentCategoryBase(
		category="POSITIVES",
		color="#4caf50",
		icon="emoji-smile",
	),
	SentimentCategoryBase(
		category="NEGATIVES",
		color="#f44336",
		icon="emoji-frown",
	),
	SentimentCategoryBase(
		category="NEUTRALS",
		color="#999999",
		icon="emoji-neutral",
	),
]

_SENTIMENTS: list[SentimentBase] = [
	# +++++++++ POSITIVES +++++++++
	SentimentBase(id_category=1, sentiment="POSITIVE"),
	SentimentBase(id_category=1, sentiment="LOVE"),
	SentimentBase(id_category=1, sentiment="HAPPY"),
	SentimentBase(id_category=1, sentiment="COURAGEOUS"),
	SentimentBase(id_category=1, sentiment="MOTIVATED"),
	SentimentBase(id_category=1, sentiment="EXCITED"),
	SentimentBase(id_category=1, sentiment="HOPEFUL"),
	SentimentBase(id_category=1, sentiment="GRATEFUL"),
	SentimentBase(id_category=1, sentiment="SATISFIED"),
	SentimentBase(id_category=1, sentiment="OPTIMISTIC"),
	SentimentBase(id_category=1, sentiment="SUCCESSFUL"),
	SentimentBase(id_category=1, sentiment="PROUD"),
	SentimentBase(id_category=1, sentiment="FUNNY"),
	SentimentBase(id_category=1, sentiment="RESPONSIBLE"),
	SentimentBase(id_category=1, sentiment="SUPPORTIVE"),
	SentimentBase(id_category=1, sentiment="PEACEFUL"),
	SentimentBase(id_category=1, sentiment="FRIENDLY"),
	SentimentBase(id_category=1, sentiment="RELIABLE"),
	SentimentBase(id_category=1, sentiment="FAIR"),

	# +++++++++ NEGATIVES +++++++++
	SentimentBase(id_category=2, sentiment="NEGATIVE"),
	SentimentBase(id_category=2, sentiment="HATE"),
	SentimentBase(id_category=2, sentiment="SAD"),
	SentimentBase(id_category=2, sentiment="ANGRY"),
	SentimentBase(id_category=2, sentiment="FRUSTRATED"),
	SentimentBase(id_category=2, sentiment="CONCERNED"),
	SentimentBase(id_category=2, sentiment="PESSIMISTIC"),
	SentimentBase(id_category=2, sentiment="IRRESPONSIBLE"),
	SentimentBase(id_category=2, sentiment="ANXIOUS"),
	SentimentBase(id_category=2, sentiment="FEARFUL"),
	SentimentBase(id_category=2, sentiment="UPSET"),
	SentimentBase(id_category=2, sentiment="ANNOYED"),
	SentimentBase(id_category=2, sentiment="UNFAIR"),
	SentimentBase(id_category=2, sentiment="CONFUSED"),
	SentimentBase(id_category=2, sentiment="SHOCKED"),
	SentimentBase(id_category=2, sentiment="VIOLENT"),
	SentimentBase(id_category=2, sentiment="RESENTFUL"),
	SentimentBase(id_category=2, sentiment="UNFRIENDLY"),
	SentimentBase(id_category=2, sentiment="UNRELIABLE"),

	# +++++++++ NEUTRALS +++++++++
	SentimentBase(id_category=3, sentiment="NEUTRAL"),
	SentimentBase(id_category=3, sentiment="INDIFFERENT"),
	SentimentBase(id_category=3, sentiment="CRITICAL"),
	SentimentBase(id_category=3, sentiment="SKEPTICAL"),
	SentimentBase(id_category=3, sentiment="CAUTIOUS"),
	SentimentBase(id_category=3, sentiment="CURIOUS"),
	SentimentBase(id_category=3, sentiment="NOVELTY"),
	SentimentBase(id_category=3, sentiment="AMBIGUOUS"),
	SentimentBase(id_category=3, sentiment="UNEMOTIONAL"),
	SentimentBase(id_category=3, sentiment="BALANCED"),
	SentimentBase(id_category=3, sentiment="CONTROVERSIAL"),
	SentimentBase(id_category=3, sentiment="MODERATE"),
	SentimentBase(id_category=3, sentiment="SURPRISED"),
	SentimentBase(id_category=3, sentiment="PASSIVE"),
	SentimentBase(id_category=3, sentiment="EXAGGERATED"),
	SentimentBase(id_category=3, sentiment="UNCERTAIN"),
]

_IDEOLOGY_CATEGORIES: list[IdeologyCategoryBase] = [
	IdeologyCategoryBase(
		category="POLITICAL_SPECTRUM",
		color="#d32f2f",
		icon="journal-medical",
	),
	IdeologyCategoryBase(
		category="ECONOMIC_ORIENTATIONS",
		color="#04796d",
		icon="currency-exchange",
	),
	IdeologyCategoryBase(
		category="NATIONAL_STANCES",
		color="#5499dd",
		icon="person-vcard",
	),
	IdeologyCategoryBase(
		category="GEOPOLITICAL_ALIGNMENTS",
		color="#ab972c",
		icon="globe2",
	),
	IdeologyCategoryBase(
		category="RELIGIOUS_ORIENTATIONS",
		color="#1ebfd4",
		icon="postage-heart",
	),
	IdeologyCategoryBase(
		category="SOCIAL_MOVEMENTS",
		color="#5d9b28",
		icon="people",
	),
	IdeologyCategoryBase(
		category="EPISTEMOLOGICAL_ORIENTATIONS",
		color="#b342e4",
		icon="pencil",
	),
]

_IDEOLOGIES: list[IdeologyBase] = [
	# +++++++++ POLITICAL SPECTRUM +++++++++
	IdeologyBase(id_category=1, ideology="LEFT_LEANING"),
	IdeologyBase(id_category=1, ideology="RIGHT_LEANING"),
	IdeologyBase(id_category=1, ideology="LIBERAL"),
	IdeologyBase(id_category=1, ideology="CONSERVATIVE"),
	IdeologyBase(id_category=1, ideology="PROGRESSIVE"),
	IdeologyBase(id_category=1, ideology="FAR_LEFT"),
	IdeologyBase(id_category=1, ideology="FAR_RIGHT"),
	IdeologyBase(id_category=1, ideology="POPULIST"),
	IdeologyBase(id_category=1, ideology="CENTRIST"),
	IdeologyBase(id_category=1, ideology="REACTIONARY"),
	IdeologyBase(id_category=1, ideology="REVOLUTIONARY"),
	IdeologyBase(id_category=1, ideology="TRADITIONALIST"),
	IdeologyBase(id_category=1, ideology="ELITIST"),
	IdeologyBase(id_category=1, ideology="SOCIAL_DEMOCRAT"),
	IdeologyBase(id_category=1, ideology="ANARCHO_CAPITALIST"),
	IdeologyBase(id_category=1, ideology="PRO_AUTHORITARIAN"),
	IdeologyBase(id_category=1, ideology="ANTI_AUTHORITARIAN"),
	IdeologyBase(id_category=1, ideology="PRO_DEMOCRACY"),
	IdeologyBase(id_category=1, ideology="ANTI_DEMOCRACY"),
	IdeologyBase(id_category=1, ideology="PRO_REPUBLIC"),
	IdeologyBase(id_category=1, ideology="ANTI_REPUBLIC"),
	IdeologyBase(id_category=1, ideology="PRO_MONARCHY"),
	IdeologyBase(id_category=1, ideology="ANTI_MONARCHY"),
	IdeologyBase(id_category=1, ideology="ANARCHIST"),
	IdeologyBase(id_category=1, ideology="TECHNOCRATIC"), # ??
	IdeologyBase(id_category=1, ideology="PRO_COMMUNIST"),
	IdeologyBase(id_category=1, ideology="ANTI_COMMUNIST"),
	IdeologyBase(id_category=1, ideology="PRO_FASCIST"),
	IdeologyBase(id_category=1, ideology="ANTI_FASCIST"),
	IdeologyBase(id_category=1, ideology="PRO_ESTABLISHMENT"),
	IdeologyBase(id_category=1, ideology="ANTI_ESTABLISHMENT"),
	

	# +++++++++ ECONOMIC ORIENTATIONS +++++++++
	IdeologyBase(id_category=2, ideology="SOCIALIST"),
	IdeologyBase(id_category=2, ideology="CAPITALIST"),
	IdeologyBase(id_category=2, ideology="PRO_LABOR"),
	IdeologyBase(id_category=2, ideology="PRO_BUSINESS"),
	IdeologyBase(id_category=2, ideology="NEOLIBERAL"),
	IdeologyBase(id_category=2, ideology="NEOSOCIALIST"),
	IdeologyBase(id_category=2, ideology="CORPORATIVIST"),
	IdeologyBase(id_category=2, ideology="FREE_TRADE"),
	IdeologyBase(id_category=2, ideology="PRO_TRADE_UNION"),
	IdeologyBase(id_category=2, ideology="ANTI_TRADE_UNION"),
	IdeologyBase(id_category=2, ideology="PRO_INDUSTRIALIZATION"),
	IdeologyBase(id_category=2, ideology="ANTI_INDUSTRIALIZATION"),
	IdeologyBase(id_category=2, ideology="PRO_AGRICULTURE"),
	IdeologyBase(id_category=2, ideology="ANTI_AGRICULTURE"),


	# +++++++++ NATIONAL STANCES +++++++++
	IdeologyBase(id_category=3, ideology="TOTALITARIAN"),
	IdeologyBase(id_category=3, ideology="FEDERALIST"),
	IdeologyBase(id_category=3, ideology="PRO_NATIONALIST"),
	IdeologyBase(id_category=3, ideology="ANTI_NATIONALIST"),
	IdeologyBase(id_category=3, ideology="ISOLATIONIST"),
	IdeologyBase(id_category=3, ideology="INTERVENTIONIST"),
	IdeologyBase(id_category=3, ideology="PRO_IMPERIALIST"),
	IdeologyBase(id_category=3, ideology="ANTI_IMPERIALIST"),
	IdeologyBase(id_category=3, ideology="PRO_GLOBALIST"),
	IdeologyBase(id_category=3, ideology="ANTI_GLOBALIST"),
	IdeologyBase(id_category=3, ideology="PROTECTIONIST"),

	# +++++++++ GEOPOLITICAL ALIGNMENTS +++++++++
	IdeologyBase(id_category=4, ideology="PRO_UNITED_STATES"),
	IdeologyBase(id_category=4, ideology="ANTI_UNITED_STATES"),
	IdeologyBase(id_category=4, ideology="PRO_CHINESE"),
	IdeologyBase(id_category=4, ideology="ANTI_CHINESE"),
	IdeologyBase(id_category=4, ideology="PRO_RUSSIAN"),
	IdeologyBase(id_category=4, ideology="ANTI_RUSSIAN"),
	IdeologyBase(id_category=4, ideology="PRO_WESTERN"),
	IdeologyBase(id_category=4, ideology="ANTI_WESTERN"),
	IdeologyBase(id_category=4, ideology="PRO_ISRAEL"),
	IdeologyBase(id_category=4, ideology="ANTI_ISRAEL"),
	IdeologyBase(id_category=4, ideology="PRO_PALESTINIAN"),
	IdeologyBase(id_category=4, ideology="ANTI_PALESTINIAN"),
	IdeologyBase(id_category=4, ideology="PRO_ARAB"),
	IdeologyBase(id_category=4, ideology="ANTI_ARAB"),
	IdeologyBase(id_category=4, ideology="PRO_IRANIAN"),
	IdeologyBase(id_category=4, ideology="ANTI_IRANIAN"),
	IdeologyBase(id_category=4, ideology="PRO_SUB_SAHARAN_AFRICAN"),
	IdeologyBase(id_category=4, ideology="ANTI_SUB_SAHARAN_AFRICAN"),
	IdeologyBase(id_category=4, ideology="PRO_LATIN_AMERICAN"),
	IdeologyBase(id_category=4, ideology="ANTI_LATIN_AMERICAN"),
	IdeologyBase(id_category=4, ideology="PRO_TAIWANESE"),
	IdeologyBase(id_category=4, ideology="ANTI_TAIWANESE"),
	IdeologyBase(id_category=4, ideology="PRO_UKRAINIAN"),
	IdeologyBase(id_category=4, ideology="ANTI_UKRAINIAN"),
	IdeologyBase(id_category=4, ideology="PRO_INDIAN"),
	IdeologyBase(id_category=4, ideology="ANTI_INDIAN"),
	IdeologyBase(id_category=4, ideology="PRO_OTAN"),
	IdeologyBase(id_category=4, ideology="ANTI_OTAN"),
	IdeologyBase(id_category=4, ideology="PRO_EUROPEAN_UNION"),
	IdeologyBase(id_category=4, ideology="ANTI_EUROPEAN_UNION"),
	IdeologyBase(id_category=4, ideology="PRO_BRICS"),
	IdeologyBase(id_category=4, ideology="ANTI_BRICS"),
	IdeologyBase(id_category=4, ideology="PRO_INTERNATIONAL_ORGANIZATIONS"),
	IdeologyBase(id_category=4, ideology="ANTI_INTERNATIONAL_ORGANIZATIONS"),

	# +++++++++ RELIGIOUS ORIENTATIONS +++++++++
	IdeologyBase(id_category=5, ideology="RELIGIOUS"),
	IdeologyBase(id_category=5, ideology="SECULAR"),
	IdeologyBase(id_category=5, ideology="PRO_CHRISTIAN"),
	IdeologyBase(id_category=5, ideology="ANTI_CHRISTIAN"),
	IdeologyBase(id_category=5, ideology="PRO_MUSLIM"),
	IdeologyBase(id_category=5, ideology="ANTI_MUSLIM"),
	IdeologyBase(id_category=5, ideology="PRO_JEWISH"),
	IdeologyBase(id_category=5, ideology="ANTI_JEWISH"),
	IdeologyBase(id_category=5, ideology="PRO_HINDU"),
	IdeologyBase(id_category=5, ideology="ANTI_HINDU"),
	IdeologyBase(id_category=5, ideology="PRO_BUDDHIST"),
	IdeologyBase(id_category=5, ideology="ANTI_BUDDHIST"),
	IdeologyBase(id_category=5, ideology="SPIRITUALIST"),

	# +++++++++ SOCIAL MOVEMENTS +++++++++
	IdeologyBase(id_category=6, ideology="PRO_SOCIAL"),
	IdeologyBase(id_category=6, ideology="ANTI_SOCIAL"),
	IdeologyBase(id_category=6, ideology="PRO_FEMINIST"),
	IdeologyBase(id_category=6, ideology="ANTI_FEMINIST"),
	IdeologyBase(id_category=6, ideology="PRO_LGBTQ"),
	IdeologyBase(id_category=6, ideology="ANTI_LGBTQ"),
	IdeologyBase(id_category=6, ideology="PRO_ANIMAL_RIGHTS"),
	IdeologyBase(id_category=6, ideology="ANTI_ANIMAL_RIGHTS"),
	IdeologyBase(id_category=6, ideology="PRO_ENVIRONMENTALIST"),
	IdeologyBase(id_category=6, ideology="ANTI_ENVIRONMENTALIST"),
	IdeologyBase(id_category=6, ideology="PRO_CLIMATE_CHANGE"),
	IdeologyBase(id_category=6, ideology="ANTI_CLIMATE_CHANGE"),
	IdeologyBase(id_category=6, ideology="PRO_LIFE"),
	IdeologyBase(id_category=6, ideology="PRO_CHOICE"),
	IdeologyBase(id_category=6, ideology="PRO_GUN"),
	IdeologyBase(id_category=6, ideology="ANTI_GUN"),
	IdeologyBase(id_category=6, ideology="PRO_IMMIGRATION"),
	IdeologyBase(id_category=6, ideology="ANTI_IMMIGRATION"),
	IdeologyBase(id_category=6, ideology="PRO_MULTICULTURALISM"),
	IdeologyBase(id_category=6, ideology="ANTI_MULTICULTURALISM"),
	IdeologyBase(id_category=6, ideology="PRO_WAR"),
	IdeologyBase(id_category=6, ideology="ANTI_WAR"),
	IdeologyBase(id_category=6, ideology="PRO_HEALTH_CARE"),
	IdeologyBase(id_category=6, ideology="ANTI_HEALTH_CARE"),
	IdeologyBase(id_category=6, ideology="PRO_HUMAN_RIGHTS"),
	IdeologyBase(id_category=6, ideology="ANTI_HUMAN_RIGHTS"),
	IdeologyBase(id_category=6, ideology="PRO_TOURISM"),
	IdeologyBase(id_category=6, ideology="ANTI_TOURISM"),

	# +++++++++ EPISTEMOLOGICAL ORIENTATIONS +++++++++
	IdeologyBase(id_category=7, ideology="IDEALIST"),
	IdeologyBase(id_category=7, ideology="INDIVIDUALIST"),
	IdeologyBase(id_category=7, ideology="UTOPIAN"),
	IdeologyBase(id_category=7, ideology="DYSTOPIAN"),
	IdeologyBase(id_category=7, ideology="MATERIALIST"),
	IdeologyBase(id_category=7, ideology="RELATIVIST"),
	IdeologyBase(id_category=7, ideology="EXISTENTIALIST"),
	IdeologyBase(id_category=7, ideology="NIHILIST"),
	IdeologyBase(id_category=7, ideology="MORALIST"),
	IdeologyBase(id_category=7, ideology="ETHICAL"),
	IdeologyBase(id_category=7, ideology="ETNOCENTRIST"),
	IdeologyBase(id_category=7, ideology="SENSATIONALIST"),
 
	IdeologyBase(id_category=7, ideology="NON_IDEOLOGICAL"),
	IdeologyBase(id_category=7, ideology="NON_POLITICAL"),
	IdeologyBase(id_category=7, ideology="NON_PARTISAN"),
	IdeologyBase(id_category=7, ideology="PRO_SCIENCE"),
	IdeologyBase(id_category=7, ideology="ANTI_SCIENCE"),
	IdeologyBase(id_category=7, ideology="PRO_EDUCATION"),
	IdeologyBase(id_category=7, ideology="ANTI_EDUCATION"),
	IdeologyBase(id_category=7, ideology="PRO_TECHNOLOGY"),
	IdeologyBase(id_category=7, ideology="ANTI_TECHNOLOGY"),
	IdeologyBase(id_category=7, ideology="PRO_CONSPIRACY_THEORIST"),
	IdeologyBase(id_category=7, ideology="ANTI_CONSPIRACY_THEORIST"),
	IdeologyBase(id_category=7, ideology="PRO_FREE_SPEECH"),
	IdeologyBase(id_category=7, ideology="ANTI_FREE_SPEECH"),
	IdeologyBase(id_category=7, ideology="MODERATE"),
	IdeologyBase(id_category=7, ideology="EXTREMIST"),
 	IdeologyBase(id_category=7, ideology="REVISIONIST"),
]
